#pragma once
//=====DATA COLLECTION PARAMETERS=====
#define ANOMALY_PERCENTAGE 10.0f

#define ENABLE_ANOMALIES 1
#define FILTER_POINTS 1
#define USE_SUBPOINTS 1
#define MAX_TICK_COUNT 10000 //27000

//=====DATA ANALYSIS PARAMATERS=====
#define ANOMALY_THRESHOLD 15.0f
#define WINDOW_SIZE 5000
#define K_PERCENTAGE 0.5f

#define TRAINING_TIME 1000
